services:
  backend-dotnet:
    build: ./backend-dotnet
    ports:
      - "5000:5000"
    environment:
      ML_SERVICE_URL: http://ml-service-python:8000
    volumes:
      - ./data:/data
    depends_on:
      - ml-service-python

  ml-service-python:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
    volumes:
      - ./ml-service-python:/app
      - ./data:/data
    environment:
      MODULE_NAME: main
      PORT: 8000
    ports:
      - "8000:8000"
